#############################################################################
# Generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#  Jun 06, 2019 10:35:08 AM CST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist {_TopLevel _vTclBalloon}
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#
    menu .pop53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Microsoft YaHei UI} 9} \
        -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop53" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m43" -background {#59d854} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x434+634+153
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1041
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "MQTT一体机  V1.5 达神互联"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m43
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men44" -activebackground {#ececec} \
        -activeforeground {#000000} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label 设置 
    menu $site_3_0.men44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {-family {Microsoft YaHei UI} -size 9} \
        -foreground black -tearoff 0 
    $site_3_0.men44 add cascade \
        -menu "$site_3_0.men44.men47" -activebackground {#ececec} \
        -activeforeground {#000000} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label 语言设置 
    set site_4_0 $site_3_0.men44
    menu $site_4_0.men47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {-family {Microsoft YaHei UI} -size 9} \
        -foreground black -tearoff 0 
    $site_4_0.men47 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -label 中文 
    $site_4_0.men47 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -label English 
    $site_3_0.men44 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -label 启动设置 
    $site_3_0 add cascade \
        -menu "$site_3_0.men44" -activebackground {#ececec} \
        -activeforeground {#000000} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label 设置 -menu "$site_3_0.men46" \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -label 关于 
    menu $site_3_0.men46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {-family {Microsoft YaHei UI} -size 9} \
        -foreground black -tearoff 0 
    $site_3_0.men46 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#63d8b9} -command {#btn_softinfo} -font TkMenuFont \
        -foreground {#ffffff} -label 软件信息 
    $site_3_0.men46 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#6ed8b5} -command {#btn_exit} -font TkMenuFont \
        -foreground {#ffffff} -label 退出 
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font "TkDefaultFont"
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo48 \
        -width 574 -height 388 -takefocus {} 
    vTcl:DefineAlias "$top.tNo48" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo48.t0 \
        -background {#d8d111} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t0" "TNotebook1_t0" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t0 \
        -padding 0 -sticky nsew -state normal -text 监控中心 -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo48.t0
    labelframe $site_4_0.lab78 \
        -font TkDefaultFont -foreground black -text 发布区 -background {#00BFFF} \
        -height 345 -highlightbackground {#d9d9d9} -highlightcolor black \
        -width 260 
    vTcl:DefineAlias "$site_4_0.lab78" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab78
    ttk::combobox $site_5_0.tCo93 \
        \
        -values {{"达神"} {"小燕子"} {"/data/#"} {"/data/alarm"} {"/data/message"} {"/data/notify"} {}} \
        -font TkTextFont -textvariable combobox_sendtopic -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo93" "TCombobox_sentopic" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo94 \
        -values {0 1 2 {}} -font TkTextFont -textvariable combobox_sendqos \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo94" "TCombobox_senqos" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa95 \
        -background {#9370DB} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 发布主题 
    vTcl:DefineAlias "$site_5_0.tLa95" "TLabel12" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa96 \
        -background {#9370DB} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 发布质量 
    vTcl:DefineAlias "$site_5_0.tLa96" "TLabel13" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font "TkDefaultFont"
    ttk::checkbutton $site_5_0.tCh97 \
        -variable tch97 -takefocus {} -text 保留上次发布 
    vTcl:DefineAlias "$site_5_0.tCh97" "TCheckbutton3" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa98 \
        -background {#9370DB} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 发布类型 
    vTcl:DefineAlias "$site_5_0.tLa98" "TLabel14" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo99 \
        -values {{"string"} {"json"} {"file"} {}} -font TkTextFont \
        -textvariable combobox_sendtype -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo99" "TCombobox_sendtype" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_5_0.tSe100 \
        -takefocus 0 
    vTcl:DefineAlias "$site_5_0.tSe100" "TSeparator2" vTcl:WidgetProc "Toplevel1" 1
    text $site_5_0.tex102 \
        -background white -font TkTextFont -foreground black -height 112 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -takefocus 0 -width 234 -wrap word 
    .top42.tNo48.t0.lab78.tex102 configure -font "TkTextFont"
    .top42.tNo48.t0.lab78.tex102 insert end text
    vTcl:DefineAlias "$site_5_0.tex102" "Text_sendmsg" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa103 \
        -background {#9370DB} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 发布内容 
    vTcl:DefineAlias "$site_5_0.tLa103" "TLabel15" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but104 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#BDB76B} -command btn_sendback \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text ⇦ 
    vTcl:DefineAlias "$site_5_0.but104" "Button_backsend" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but105 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#BDB76B} -command btn_sendclear \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text ✖ 
    vTcl:DefineAlias "$site_5_0.but105" "Button_clearsend" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but106 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#78C300} -command btn_send -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -takefocus 0 -text 发布 
    vTcl:DefineAlias "$site_5_0.but106" "Button_publish" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but43 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#78C300} -command btn_selectfile \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text {. . .} 
    vTcl:DefineAlias "$site_5_0.but43" "Button_selectfile" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.tCo93 \
        -in $site_5_0 -x 80 -y 20 -anchor nw -bordermode ignore 
    place $site_5_0.tCo94 \
        -in $site_5_0 -x 80 -y 60 -anchor nw -bordermode ignore 
    place $site_5_0.tLa95 \
        -in $site_5_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_5_0.tLa96 \
        -in $site_5_0 -x 10 -y 60 -anchor nw -bordermode ignore 
    place $site_5_0.tCh97 \
        -in $site_5_0 -x 10 -y 90 -width 105 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa98 \
        -in $site_5_0 -x 10 -y 130 -width 52 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tCo99 \
        -in $site_5_0 -x 80 -y 130 -width 160 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tSe100 \
        -in $site_5_0 -x 10 -y 140 -width 230 -anchor nw -bordermode inside 
    place $site_5_0.tex102 \
        -in $site_5_0 -x 10 -y 190 -width 234 -relwidth 0 -height 112 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa103 \
        -in $site_5_0 -x 10 -y 170 -anchor nw -bordermode ignore 
    place $site_5_0.but104 \
        -in $site_5_0 -x 10 -y 310 -width 40 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but105 \
        -in $site_5_0 -x 100 -y 310 -width 40 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but106 \
        -in $site_5_0 -x 180 -y 310 -width 60 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but43 \
        -in $site_5_0 -x 200 -y 90 -width 40 -relwidth 0 -anchor nw \
        -bordermode ignore 
    labelframe $site_4_0.lab79 \
        -font TkDefaultFont -foreground black -text 订阅区 -background {#78C300} \
        -height 345 -highlightbackground {#d9d9d9} -highlightcolor black \
        -width 250 
    vTcl:DefineAlias "$site_4_0.lab79" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab79
    ttk::style configure Treeview.Heading -background #d9d9d9
    ttk::style configure Treeview.Heading -font "TkDefaultFont"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_5_0.scr80 \
        -background {#d9d9d9} -height 15 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 30 
    vTcl:DefineAlias "$site_5_0.scr80" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1
        .top42.tNo48.t0.lab79.scr80.01 configure -columns {Col1 Col2}
        .top42.tNo48.t0.lab79.scr80.01 heading #0 -text {序号}
        .top42.tNo48.t0.lab79.scr80.01 heading #0 -anchor center
        .top42.tNo48.t0.lab79.scr80.01 column #0 -width 54
        .top42.tNo48.t0.lab79.scr80.01 column #0 -minwidth 20
        .top42.tNo48.t0.lab79.scr80.01 column #0 -stretch 1
        .top42.tNo48.t0.lab79.scr80.01 column #0 -anchor w
        .top42.tNo48.t0.lab79.scr80.01 heading Col1 -text {主题}
        .top42.tNo48.t0.lab79.scr80.01 heading Col1 -anchor center
        .top42.tNo48.t0.lab79.scr80.01 column Col1 -width 111
        .top42.tNo48.t0.lab79.scr80.01 column Col1 -minwidth 20
        .top42.tNo48.t0.lab79.scr80.01 column Col1 -stretch 1
        .top42.tNo48.t0.lab79.scr80.01 column Col1 -anchor center
        .top42.tNo48.t0.lab79.scr80.01 heading Col2 -text {质量}
        .top42.tNo48.t0.lab79.scr80.01 heading Col2 -anchor center
        .top42.tNo48.t0.lab79.scr80.01 column Col2 -width 51
        .top42.tNo48.t0.lab79.scr80.01 column Col2 -minwidth 20
        .top42.tNo48.t0.lab79.scr80.01 column Col2 -stretch 1
        .top42.tNo48.t0.lab79.scr80.01 column Col2 -anchor center
    ttk::label $site_5_0.tLa81 \
        -background {#00BFFF} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 已订阅内容列表 
    vTcl:DefineAlias "$site_5_0.tLa81" "TLabel9" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo84 \
        \
        -values {{"达神"} {"小燕子"} {"/data/#"} {"/data/alarm"} {"/data/message"} {"/data/notify"} {}} \
        -font TkTextFont -textvariable combobox_subtopic -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo84" "TCombobox_subtopic" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo85 \
        -values {0 1 2} -font TkTextFont -textvariable combobox_subqos \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo85" "TCombobox_subqos" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa86 \
        -background {#9370DB} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 订阅主题 
    vTcl:DefineAlias "$site_5_0.tLa86" "TLabel10" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa88 \
        -background {#9370DB} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 订阅质量 
    vTcl:DefineAlias "$site_5_0.tLa88" "TLabel11" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_5_0.tSe90 \
        -takefocus 0 
    vTcl:DefineAlias "$site_5_0.tSe90" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but109 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#00BFFF} -command btn_cancelsub \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text 取消所选订阅 
    vTcl:DefineAlias "$site_5_0.but109" "Button_cancelsub" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but110 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#00BFFF} -command btn_clearsub \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text 清空订阅列表 
    vTcl:DefineAlias "$site_5_0.but110" "Button_clearsub" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but111 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#00BFFF} -command btn_addsub \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text 添加订阅 
    vTcl:DefineAlias "$site_5_0.but111" "Button_addsub" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.scr80 \
        -in $site_5_0 -x 10 -y 40 -width 235 -relwidth 0 -height 100 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa81 \
        -in $site_5_0 -x 80 -y 10 -anchor nw -bordermode ignore 
    place $site_5_0.tCo84 \
        -in $site_5_0 -x 30 -y 220 -anchor nw -bordermode ignore 
    place $site_5_0.tCo85 \
        -in $site_5_0 -x 30 -y 280 -anchor nw -bordermode ignore 
    place $site_5_0.tLa86 \
        -in $site_5_0 -x 70 -y 190 -anchor nw -bordermode ignore 
    place $site_5_0.tLa88 \
        -in $site_5_0 -x 70 -y 250 -anchor nw -bordermode ignore 
    place $site_5_0.tSe90 \
        -in $site_5_0 -x -2 -y 156 -width 240 -anchor nw -bordermode inside 
    place $site_5_0.but109 \
        -in $site_5_0 -x 10 -y 140 -anchor nw -bordermode ignore 
    place $site_5_0.but110 \
        -in $site_5_0 -x 160 -y 140 -anchor nw -bordermode ignore 
    place $site_5_0.but111 \
        -in $site_5_0 -x 70 -y 310 -anchor nw -bordermode ignore 
    place $site_4_0.lab78 \
        -in $site_4_0 -x 0 -y 10 -width 260 -relwidth 0 -height 345 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab79 \
        -in $site_4_0 -x 290 -y 10 -width 250 -relwidth 0 -height 345 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo48.t2 \
        -background {#88d8cd} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t2" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t2 \
        -padding 0 -sticky nsew -state normal -text 消息中心 -image {} \
        -compound none -underline -1 
    set site_4_1  $top.tNo48.t2
    frame $site_4_1.fra45 \
        -borderwidth 2 -relief groove -background {#d8ac72} -height 335 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 535 
    vTcl:DefineAlias "$site_4_1.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_1.fra45
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_5_0.scr46 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_5_0.scr46" "Scrolledtext1" vTcl:WidgetProc "Toplevel1" 1

    $site_5_0.scr46.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -takefocus 0 \
        -width 10 \
        -wrap none
    vTcl:copy_lock $site_5_0.scr46
    button $site_5_0.but47 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#78C300} -command btn_savemsg \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text 消息入库 
    vTcl:DefineAlias "$site_5_0.but47" "Button_savemsg" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but48 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#78C300} -command btn_readhistory \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text 查看历史消息 
    vTcl:DefineAlias "$site_5_0.but48" "Button_readhistory" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but49 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#78C300} -command btn_clearmsg \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text 清空消息 
    vTcl:DefineAlias "$site_5_0.but49" "Button_clearmsg" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font "TkDefaultFont"
    ttk::checkbutton $site_5_0.tCh50 \
        -variable tch50 -takefocus {} -text 消息自动入库 
    vTcl:DefineAlias "$site_5_0.tCh50" "TCheckbutton_automsgsave" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but44 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#78C300} -command btn_savefiles \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text 保存到文件 
    vTcl:DefineAlias "$site_5_0.but44" "Button_savefiles" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.scr46 \
        -in $site_5_0 -x 10 -y 10 -width 511 -relwidth 0 -height 285 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but47 \
        -in $site_5_0 -x 240 -y 300 -anchor nw -bordermode ignore 
    place $site_5_0.but48 \
        -in $site_5_0 -x 330 -y 300 -anchor nw -bordermode ignore 
    place $site_5_0.but49 \
        -in $site_5_0 -x 450 -y 300 -anchor nw -bordermode ignore 
    place $site_5_0.tCh50 \
        -in $site_5_0 -x 10 -y 300 -width 100 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but44 \
        -in $site_5_0 -x 140 -y 300 -anchor nw -bordermode ignore 
    place $site_4_1.fra45 \
        -in $site_4_1 -x 10 -y 10 -width 535 -relwidth 0 -height 335 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo48.t1 \
        -background {#4389d8} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t1 \
        -padding 0 -sticky nsew -state normal -text 连接设置 -image {} \
        -compound left -underline -1 
    set site_4_2  $top.tNo48.t1
    ttk::entry $site_4_2.tEn50 \
        -font TkTextFont -textvariable entrytv_clientname -foreground {} \
        -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_4_2.tEn50" "TEntry_clientname" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $site_4_2.tEn51 \
        -font TkTextFont -textvariable entrytv_clientid -foreground {} \
        -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$site_4_2.tEn51" "TEntry_clientid" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_2.tLa59 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text MQTT客户端名称 
    vTcl:DefineAlias "$site_4_2.tLa59" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_2.tLa60 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text MQTT客户端ID 
    vTcl:DefineAlias "$site_4_2.tLa60" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_2.tLa61 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text MQTT服务器类型 
    vTcl:DefineAlias "$site_4_2.tLa61" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_2.tLa63 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text MQTT连接协议 
    vTcl:DefineAlias "$site_4_2.tLa63" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_2.tLa64 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text MQTT服务器地址 
    vTcl:DefineAlias "$site_4_2.tLa64" "TLabel5" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_2.tLa65 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text MQTT服务器端口号 
    vTcl:DefineAlias "$site_4_2.tLa65" "TLabel6" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_2.tLa66 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 设备用户名 
    vTcl:DefineAlias "$site_4_2.tLa66" "TLabel7" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_2.tLa67 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 设备密码 
    vTcl:DefineAlias "$site_4_2.tLa67" "TLabel8" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font "TkDefaultFont"
    ttk::checkbutton $site_4_2.tCh68 \
        -variable tch68 -takefocus {} -text 自动连接 
    vTcl:DefineAlias "$site_4_2.tCh68" "TCheckbutton_autoconnect" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_2.tCo70 \
        -values {{"EMQ"} {"Apollo"}} -font TkTextFont \
        -textvariable combobox_servertype -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_2.tCo70" "TCombobox_mqtype" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_2.tCo71 \
        -values {{"tcp"} {"ws"} {"ssl"}} -font TkTextFont \
        -textvariable combobox_mqsl -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_2.tCo71" "TCombobox_mqsl" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_2.tCo72 \
        -values {1883 8083 8883 61613 61623} -font TkTextFont \
        -textvariable combobox_mqport -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_2.tCo72" "TCombobox_mqport" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_2.tCo73 \
        -values {{"127.0.0.1"} {"47.93.30.53"}} -font TkTextFont \
        -textvariable combobox_mqip -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_2.tCo73" "TCombobox_mqip" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_2.tCo74 \
        -values {{"admin"} {"dashen"}} -font TkTextFont \
        -textvariable combobox_username -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_2.tCo74" "TCombobox_username" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_4_2.tCo75 \
        -values {{"public"} {"admin"} {"123456"}} -font TkTextFont -show * \
        -textvariable combobox_pwd -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_2.tCo75" "TCombobox_pwd" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font "TkDefaultFont"
    ttk::checkbutton $site_4_2.tCh76 \
        -variable tch76 -takefocus {} -text 自动默认 
    vTcl:DefineAlias "$site_4_2.tCh76" "TCheckbutton_automoren" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but107 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#00BFFF} -command btn_showhide \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text 显示 
    vTcl:DefineAlias "$site_4_2.but107" "Button_showhide" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but108 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#00BFFF} -command btn_randomgerner \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text 随机生成 
    vTcl:DefineAlias "$site_4_2.but108" "Button_randomgener" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_2.but112 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#00BFFF} -command btn_savesettings \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text 保存设置 
    vTcl:DefineAlias "$site_4_2.but112" "Button_savesettings" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_2.tEn50 \
        -in $site_4_2 -x 20 -y 40 -anchor nw -bordermode ignore 
    place $site_4_2.tEn51 \
        -in $site_4_2 -x 220 -y 40 -anchor nw -bordermode ignore 
    place $site_4_2.tLa59 \
        -in $site_4_2 -x 40 -y 10 -anchor nw -bordermode ignore 
    place $site_4_2.tLa60 \
        -in $site_4_2 -x 250 -y 10 -anchor nw -bordermode ignore 
    place $site_4_2.tLa61 \
        -in $site_4_2 -x 40 -y 70 -anchor nw -bordermode ignore 
    place $site_4_2.tLa63 \
        -in $site_4_2 -x 250 -y 70 -anchor nw -bordermode ignore 
    place $site_4_2.tLa64 \
        -in $site_4_2 -x 40 -y 130 -anchor nw -bordermode ignore 
    place $site_4_2.tLa65 \
        -in $site_4_2 -x 240 -y 130 -anchor nw -bordermode ignore 
    place $site_4_2.tLa66 \
        -in $site_4_2 -x 60 -y 190 -anchor nw -bordermode ignore 
    place $site_4_2.tLa67 \
        -in $site_4_2 -x 270 -y 190 -anchor nw -bordermode ignore 
    place $site_4_2.tCh68 \
        -in $site_4_2 -x 20 -y 290 -width 80 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.tCo70 \
        -in $site_4_2 -x 20 -y 100 -anchor nw -bordermode ignore 
    place $site_4_2.tCo71 \
        -in $site_4_2 -x 220 -y 100 -anchor nw -bordermode ignore 
    place $site_4_2.tCo72 \
        -in $site_4_2 -x 220 -y 160 -anchor nw -bordermode ignore 
    place $site_4_2.tCo73 \
        -in $site_4_2 -x 20 -y 160 -anchor nw -bordermode ignore 
    place $site_4_2.tCo74 \
        -in $site_4_2 -x 20 -y 220 -anchor nw -bordermode ignore 
    place $site_4_2.tCo75 \
        -in $site_4_2 -x 220 -y 220 -anchor nw -bordermode ignore 
    place $site_4_2.tCh76 \
        -in $site_4_2 -x 390 -y 160 -width 75 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_2.but107 \
        -in $site_4_2 -x 390 -y 220 -width 50 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_4_2.but108 \
        -in $site_4_2 -x 370 -y 40 -anchor nw -bordermode ignore 
    place $site_4_2.but112 \
        -in $site_4_2 -x 140 -y 290 -anchor nw -bordermode ignore 
    frame $top.tNo48.t3 \
        -background {#fffff0} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t3" "TNotebook1_t3" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t3 \
        -padding 0 -sticky nsew -state normal -text 定时助手 -image {} \
        -compound none -underline -1 
    set site_4_3  $top.tNo48.t3
    labelframe $site_4_3.lab49 \
        -font TkDefaultFont -foreground black -text 天气采集推送模块 \
        -background {#5bd878} -height 155 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 240 
    vTcl:DefineAlias "$site_4_3.lab49" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_3.lab49
    ttk::label $site_5_0.tLa53 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 监控地区 
    vTcl:DefineAlias "$site_5_0.tLa53" "TLabel16" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa54 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 推送间隔 
    vTcl:DefineAlias "$site_5_0.tLa54" "TLabel17" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but59 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#00BFFF} -command btn_tianqi \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text 开启天气推送 
    vTcl:DefineAlias "$site_5_0.but59" "Button_tq" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo63 \
        -values {{"北京"} {"自贡"} {}} -font TkTextFont \
        -textvariable combobox_area -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo63" "TCombobox_area" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo64 \
        -values {{"600"} {"3600"} {"18000"} {"36000"} {"72000"} {"86400"} {}} \
        -font TkTextFont -textvariable combobox_tqtime -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo64" "TCombobox_tqtime" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.tLa53 \
        -in $site_5_0 -x 10 -y 30 -anchor nw -bordermode ignore 
    place $site_5_0.tLa54 \
        -in $site_5_0 -x 10 -y 70 -anchor nw -bordermode ignore 
    place $site_5_0.but59 \
        -in $site_5_0 -x 10 -y 120 -anchor nw -bordermode ignore 
    place $site_5_0.tCo63 \
        -in $site_5_0 -x 90 -y 30 -width 143 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tCo64 \
        -in $site_5_0 -x 90 -y 70 -width 143 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_3.lab50 \
        -font TkDefaultFont -foreground black -text 新闻采集推送模块 \
        -background {#d8b259} -height 155 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 270 
    vTcl:DefineAlias "$site_4_3.lab50" "Labelframe4" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_3.lab50
    ttk::label $site_5_0.tLa57 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 监控网址 
    vTcl:DefineAlias "$site_5_0.tLa57" "TLabel20" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa58 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 推送间隔 
    vTcl:DefineAlias "$site_5_0.tLa58" "TLabel21" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but61 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#00BFFF} -command btn_news -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -takefocus 0 -text 开启新闻推送 
    vTcl:DefineAlias "$site_5_0.but61" "Button_news" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo65 \
        -font TkTextFont -textvariable combobox_website -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo65" "TCombobox_website" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo66 \
        -values {{"600"} {"3600"} {"18000"} {"36000"} {"72000"} {"86400"}} \
        -font TkTextFont -textvariable combobox_newstime -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo66" "TCombobox_newstime" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.tLa57 \
        -in $site_5_0 -x 10 -y 30 -anchor nw -bordermode ignore 
    place $site_5_0.tLa58 \
        -in $site_5_0 -x 10 -y 60 -anchor nw -bordermode ignore 
    place $site_5_0.but61 \
        -in $site_5_0 -x 10 -y 120 -anchor nw -bordermode ignore 
    place $site_5_0.tCo65 \
        -in $site_5_0 -x 80 -y 30 -width 143 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tCo66 \
        -in $site_5_0 -x 80 -y 60 -width 143 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_3.lab51 \
        -font TkDefaultFont -foreground black -text 室温采集自动开空凋模块 \
        -background {#86d8af} -height 175 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 550 
    vTcl:DefineAlias "$site_4_3.lab51" "Labelframe5" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_3.lab51
    ttk::label $site_5_0.tLa55 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 室内最低温度 
    vTcl:DefineAlias "$site_5_0.tLa55" "TLabel18" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa56 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 推送间隔 
    vTcl:DefineAlias "$site_5_0.tLa56" "TLabel19" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but60 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#00BFFF} -command btn_temp -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -takefocus 0 -text 开启室温推送 
    vTcl:DefineAlias "$site_5_0.but60" "Button_tem" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo67 \
        -font TkTextFont -textvariable combobox_lowtem -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo67" "TCombobox_lowtem" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo68 \
        -values {{"600"} {"3600"} {"18000"} {"36000"} {"72000"} {"86400"}} \
        -font TkTextFont -textvariable combobox_temtime -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo68" "TCombobox_temtime" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font "TkDefaultFont"
    ttk::checkbutton $site_5_0.tCh69 \
        -variable tch69 -takefocus {} -text 超过最高温度自动开启空调 
    vTcl:DefineAlias "$site_5_0.tCh69" "TCheckbutton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa70 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 室内最高温度 
    vTcl:DefineAlias "$site_5_0.tLa70" "TLabel22" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo71 \
        -font TkTextFont -textvariable combobox_hightem -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo71" "TCombobox_hightem" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font "TkDefaultFont"
    ttk::checkbutton $site_5_0.tCh72 \
        -variable tch72 -takefocus {} -text 低于最低温度自动关闭空调 
    vTcl:DefineAlias "$site_5_0.tCh72" "TCheckbutton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa73 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 默认空调温度 
    vTcl:DefineAlias "$site_5_0.tLa73" "TLabel23" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_5_0.tCo75 \
        -values {16 20 25} -font TkTextFont -textvariable combobox_deftem \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tCo75" "TCombobox_deftem" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa76 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -text 设置空调度数 
    vTcl:DefineAlias "$site_5_0.tLa76" "TLabel24" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_5_0.scr79 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_5_0.scr79" "Scrolledlistbox1" vTcl:WidgetProc "Toplevel1" 1

    $site_5_0.scr79.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -takefocus 0 \
        -width 10
    button $site_5_0.but80 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#00BFFF} -command btn_settemp \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text 确认调温 
    vTcl:DefineAlias "$site_5_0.but80" "Button_sertem" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.tLa55 \
        -in $site_5_0 -x 10 -y 30 -anchor nw -bordermode ignore 
    place $site_5_0.tLa56 \
        -in $site_5_0 -x 10 -y 90 -anchor nw -bordermode ignore 
    place $site_5_0.but60 \
        -in $site_5_0 -x 10 -y 140 -anchor nw -bordermode ignore 
    place $site_5_0.tCo67 \
        -in $site_5_0 -x 110 -y 30 -width 113 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tCo68 \
        -in $site_5_0 -x 110 -y 90 -width 113 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tCh69 \
        -in $site_5_0 -x 260 -y 30 -width 180 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa70 \
        -in $site_5_0 -x 10 -y 60 -anchor nw -bordermode ignore 
    place $site_5_0.tCo71 \
        -in $site_5_0 -x 110 -y 60 -width 113 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tCh72 \
        -in $site_5_0 -x 260 -y 60 -width 180 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa73 \
        -in $site_5_0 -x 260 -y 100 -anchor nw -bordermode ignore 
    place $site_5_0.tCo75 \
        -in $site_5_0 -x 340 -y 100 -width 83 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa76 \
        -in $site_5_0 -x 260 -y 130 -anchor nw -bordermode ignore 
    place $site_5_0.scr79 \
        -in $site_5_0 -x 340 -y 130 -width 91 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but80 \
        -in $site_5_0 -x 450 -y 130 -anchor nw -bordermode ignore 
    place $site_4_3.lab49 \
        -in $site_4_3 -x 10 -y 10 -width 240 -relwidth 0 -height 155 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.lab50 \
        -in $site_4_3 -x 290 -y 10 -width 270 -relwidth 0 -height 155 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_3.lab51 \
        -in $site_4_3 -x 10 -y 170 -width 550 -relwidth 0 -height 175 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo48.t4 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo48.t4" "TNotebook1_t4" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo48 add $top.tNo48.t4 \
        -padding 0 -sticky nsew -state normal -text 语音助手 -image {} \
        -compound none -underline -1 
    set site_4_4  $top.tNo48.t4
    labelframe $site_4_4.lab43 \
        -font TkDefaultFont -foreground {#ffffff} -text 语音助手设置 \
        -background {#496fd8} -height 345 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 310 
    vTcl:DefineAlias "$site_4_4.lab43" "Labelframe6" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_4.lab43
    ttk::label $site_5_0.tLa44 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -text 语速设置 
    vTcl:DefineAlias "$site_5_0.tLa44" "TLabel25" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.tLa44 <<SetBalloon>> {
        set ::vTcl::balloon::%W {语速设置从0到10，依次增加}
    }
    ttk::label $site_5_0.tLa45 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -text 语调设置 
    vTcl:DefineAlias "$site_5_0.tLa45" "TLabel26" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.tLa45 <<SetBalloon>> {
        set ::vTcl::balloon::%W {语调设置从0到10，依次增加}
    }
    ttk::label $site_5_0.tLa46 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -text 音量设置 
    vTcl:DefineAlias "$site_5_0.tLa46" "TLabel27" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.tLa46 <<SetBalloon>> {
        set ::vTcl::balloon::%W {音调设置从0到10，依次增加}
    }
    ttk::label $site_5_0.tLa47 \
        -background {#78C300} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -text 发音人设置 
    vTcl:DefineAlias "$site_5_0.tLa47" "TLabel28" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.tLa47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {发音人总共支持5种，从小到大分别是
普通男，普通女，情感男，情感女，萝莉女，职场女}
    }
    spinbox $site_5_0.spi52 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} -font font9 \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable spinbox_setspd -to 100.0 -values {0 1 2 3 4 5 6 7 {}} 
    vTcl:DefineAlias "$site_5_0.spi52" "Spinbox_spd" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_5_0.spi53 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} -font font9 \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable spinbox_setpit -to 100.0 \
        -values {0 1 2 3 4 5 6 7 8 9 10} 
    vTcl:DefineAlias "$site_5_0.spi53" "Spinbox_pit" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_5_0.spi54 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} -font font9 \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable spinbox_setvol -to 100.0 \
        -values {0 1 2 3 4 5 6 7 8 9 10} 
    vTcl:DefineAlias "$site_5_0.spi54" "Spinbox_vol" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_5_0.spi56 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} -font font9 \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable spinbox_setper -to 100.0 -values {0 1 2 3 4 5} 
    vTcl:DefineAlias "$site_5_0.spi56" "Spinbox_per" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font "TkDefaultFont"
    ttk::checkbutton $site_5_0.tCh58 \
        -variable tch58 -takefocus {} -text 启用消息语音通知 
    vTcl:DefineAlias "$site_5_0.tCh58" "TCheckbutton_yuyinopen" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but59 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#00BFFF} -command btn_readyuyinset \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 查看设置说明 
    vTcl:DefineAlias "$site_5_0.but59" "Button_readset" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but60 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#00BFFF} -command btn_saveyuyinset \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text 保存助手设置 
    vTcl:DefineAlias "$site_5_0.but60" "Button_saveyuyinset" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font "TkDefaultFont"
    ttk::button $site_5_0.tBu61 \
        -command btn_setupyuyin -takefocus {} -text 安装语音助手 
    vTcl:DefineAlias "$site_5_0.tBu61" "TButton_setup" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font "TkDefaultFont"
    ttk::button $site_5_0.tBu62 \
        -command btn_uninstallyuyin -takefocus {} -text 卸载语音助手 
    vTcl:DefineAlias "$site_5_0.tBu62" "TButton_uninstall" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font "TkDefaultFont"
    ttk::checkbutton $site_5_0.tCh43 \
        -variable varcheck_delyuyin -takefocus {} -text 自动删除语音文件 
    vTcl:DefineAlias "$site_5_0.tCh43" "TCheckbutton_delyuyin" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.tCh43 <<SetBalloon>> {
        set ::vTcl::balloon::%W {勾选本选项后，每次收到的语音消息
将在程序结束后自动删除，不可保存}
    }
    place $site_5_0.tLa44 \
        -in $site_5_0 -x 10 -y 40 -anchor nw -bordermode ignore 
    place $site_5_0.tLa45 \
        -in $site_5_0 -x 10 -y 80 -anchor nw -bordermode ignore 
    place $site_5_0.tLa46 \
        -in $site_5_0 -x 10 -y 130 -anchor nw -bordermode ignore 
    place $site_5_0.tLa47 \
        -in $site_5_0 -x 10 -y 180 -anchor nw -bordermode ignore 
    place $site_5_0.spi52 \
        -in $site_5_0 -x 80 -y 40 -anchor nw -bordermode ignore 
    place $site_5_0.spi53 \
        -in $site_5_0 -x 80 -y 80 -anchor nw -bordermode ignore 
    place $site_5_0.spi54 \
        -in $site_5_0 -x 80 -y 130 -anchor nw -bordermode ignore 
    place $site_5_0.spi56 \
        -in $site_5_0 -x 80 -y 180 -anchor nw -bordermode ignore 
    place $site_5_0.tCh58 \
        -in $site_5_0 -x 10 -y 230 -width 125 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but59 \
        -in $site_5_0 -x 110 -y 300 -anchor nw -bordermode ignore 
    place $site_5_0.but60 \
        -in $site_5_0 -x 160 -y 230 -width 79 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu61 \
        -in $site_5_0 -x 10 -y 300 -anchor nw -bordermode ignore 
    place $site_5_0.tBu62 \
        -in $site_5_0 -x 200 -y 300 -anchor nw -bordermode ignore 
    place $site_5_0.tCh43 \
        -in $site_5_0 -x 10 -y 260 -width 125 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_4.lab44 \
        -font TkDefaultFont -foreground {#4040ff} -text 下载进度展示栏 \
        -background {#d9d9d9} -height 345 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 240 
    vTcl:DefineAlias "$site_4_4.lab44" "Labelframe7" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_4.lab44
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_5_0.scr45 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_5_0.scr45" "Scrolledlistbox_xiazai" vTcl:WidgetProc "Toplevel1" 1

    $site_5_0.scr45.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font font10 \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -listvariable list_xiazai
    place $site_5_0.scr45 \
        -in $site_5_0 -x 0 -y 20 -width 231 -relwidth 0 -height 311 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_4.lab43 \
        -in $site_4_4 -x 10 -y 10 -width 310 -relwidth 0 -height 345 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_4.lab44 \
        -in $site_4_4 -x 330 -y 10 -width 240 -relwidth 0 -height 345 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $top.but43 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#00BFFF} -command btn_connect \
        -disabledforeground {#a3a3a3} -font TkDefaultFont \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text 开始连接 
    vTcl:DefineAlias "$top.but43" "Button_connect" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar $top.tPr43 \
        -variable tpb_send -value 0.5 -takefocus 0 
    vTcl:DefineAlias "$top.tPr43" "TProgressbar1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa44 \
        -background {#00BFFF} -foreground {#ffffff} -font TkDefaultFont \
        -relief flat -takefocus 0 -textvariable labletv_jindu 
    vTcl:DefineAlias "$top.tLa44" "TLabel_jindu" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $top.tEn43 \
        -font TkTextFont -textvariable entrytv_filepath -foreground {} \
        -background {} -takefocus {} -cursor ibeam 
    vTcl:DefineAlias "$top.tEn43" "TEntry_filepath" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo48 \
        -in $top -x 10 -y 40 -width 574 -relwidth 0 -height 388 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but43 \
        -in $top -x 10 -y 10 -width 100 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.tPr43 \
        -in $top -x 380 -y 10 -width 150 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa44 \
        -in $top -x 530 -y 10 -width 50 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tEn43 \
        -in $top -x 150 -y 10 -width 216 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

